---
version: "3.2"
services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    hostname: postgresql
    volumes:
      - auth-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:?database password required}
      - POSTGRES_USER=${PG_USER:-authentik}
      - POSTGRES_DB=${PG_DB:-authentik}
    networks:
      - auth-secure

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    hostname: redis
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - auth-redis:/data
    networks:
      - auth-secure

  authentik-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.5.3}
    restart: unless-stopped
    hostname: authentik
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${DB_PASS}
      - AUTHENTIK_SECRET_KEY={AUTHENTIK_SECRET_KEY}
    volumes:
      - auth-appdata:/media
      - auth-appdata:/templates

    ports:
      - ${AUTH_PORT_HTTP}:9000
      - ${AUTH_PORT_HTTPS}:9443
    depends_on:
      - postgresql
      - redis
    networks:
      - auth-secure
      - proxynet
  authentik-worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.5.3}
    restart: unless-stopped
    hostname: authentik-worker
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${DB_PASS}
      - AUTHENTIK_SECRET_KEY={AUTHENTIK_SECRET_KEY}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - auth-appdata:/media
      - auth-appdata:/certs
      - auth-appdata:/templates
    depends_on:
      - postgresql
      - redis
    networks:
      - auth-secure
      - proxynet

volumes:
  auth-database:
    driver: local
  auth-redis:
    driver: local
  auth-appdata:
    driver: local
networks:
  proxynet:
    driver: bridge
    external: true
  auth-secure:
    driver: bridge
    external: true
