---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    hostname: radarr
    ports:
      - 7878:7878
    volumes:
      - radarr-data:/config
      - ${downloads}:/downloads
      - ${movies}:/movies
    networks:
      - proxynet

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    hostname: sonarr
    ports:
      - 8989:8989
    volumes:
      - sonarr-data:/config
      - ${downloads}:/downloads
      - ${tv}:/tv
    networks:
      - proxynet
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    hostname: sabnzbd
    ports:
      - 8383:8383
      - 9090:9090
    volumes:
      - sabnzbd-data:/config
      - ${downloads}:/downloads

    networks:
      - proxynet
  prowlarr:
    image: linuxserver/prowlarr:develop
    restart: unless-stopped
    hostname: prowlarr
    ports:
      - 9696:9696
    volumes:
      - prowlarr-data:/config

    networks:
      - proxynet
  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    hostname: bazarr
    ports:
      - 6767:6767
    volumes:
      - bazarr-data:/config
      - ${tv}:/tv
      - ${movies}:/movies


    networks:
      - proxynet
  lidarr:
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    hostname: lidarr
    ports:
      - 8686:8686
    volumes:
      - lidarr-data:/config
      - ${downloads}:/downloads
      - ${music}:/music
    networks:
      - proxynet
  overseerr:
    image: linuxserver/overseerr:latest
    restart: unless-stopped
    hostname: overseerr
    ports:
      - 5055:5055
    volumes:
      - overseerr-data:/config

    networks:
      - proxynet

volumes:
  radarr-data:
    driver: local
  sonarr-data:
    driver: local
  sabnzbd-data:
    driver: local
  prowlarr-data:
    driver: local
  bazarr-data:
    driver: local
  overseerr-data:
    driver: local
  lidarr-data:
    driver: local


networks:
  proxynet:
    driver: bridge
    external: true
