---
version: "3.2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    hostname: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
      - nextcloudconfig:/config
      - ${DATADRIVE}:/data
    ports:
      - 444:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
    networks:
      - proxynet
      - next-secure

  nextcloud_db:
    image: registry.hub.docker.com/library/postgres:14
    restart: unless-stopped
    hostname: nextcloud_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - nextclouddatabase:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud_db

    networks:
      - next-secure

      
networks:
  proxynet:
    external: true
  next-secure:
    driver: "bridge"

         

volumes:
  nextclouddatabase:
    driver: local
  nextcloudconfig:
    driver: local
    
