---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=99
      - PGID=100
      - TZ=${TZ}
    volumes:
      - nextcloudconfig:/config
      - ${DATADRIVE}:/data
    ports:
      - ${PORT}:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
    networks:
      - ${SECURENET}
      - ${PROXYNET}
    env_file:
      - .env
  nextcloud_db:
    image: registry.hub.docker.com/library/postgres:14
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - nextclouddatabase:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud_db

    networks:
      - ${SECURENET}
    env_file:
      - .env
      
networks:
  ${PROXYNET}:
    external:                                                                                                                                                                  
         name: ${PROXYNET}
  ${SECURENET}:
    external:                                                                                                                                                                  
         name: ${SECURENET}

volumes:
  nextclouddatabase:
    driver: local
  nextcloudconfig:
    driver: local
    
